global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: cisco

    metrics_path: /metrics/v1

    scheme: https
    oauth2:
        client_id: "CLIENT_ID"
        client_secret: "CLIENT_SECRET"
        scopes:
          - metrics.read
        token_url: "https://id.wgtwo.com/oauth2/token"

    static_configs:
      - targets:
          - "api.wgtwo.com:443" # Dublin
          - "api.sakura.wgtwo.com:443" # Tokyo
          - "api.oak.wgtwo.com:443" # Oregon
