global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: wgtwo

    metrics_path: /metrics/v1

    scheme: https
    basic_auth:
      username: "CLIENT_ID"
      password: "CLIENT_SECRET"

    static_configs:
      - targets:
          - "api.wgtwo.com:443"
